apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitconsumer
spec:
  selector:
    matchLabels:
      app: rabbitconsumer
  template:
    metadata:
      labels:
        app: rabbitconsumer
    spec:
      containers:
        - name: rabbitconsumer
          image: kxingjing/question-3b:1.0
          env:
            - name: RABBITMQ_HOST
              value: "rabbitmq"
            - name: RABBITMQ_PORT
              value: "5672"
